version: "2"
services:
  rehlds:
    image: dapize/hlds:latest
    environment:
      SERVER_NAME: "My ReHL Server"
      START_MAP: "crossfire"
      MAXPLAYERS: "32"
      RCON_PASSWORD: "secret"
    ports:
      - 26900:26900/udp
      - 27020:27020/udp
      - 27015:27015/udp
      - 27015:27015/tcp
